# Site settings
description: "Principal Product Security Analyst"
baseurl: ""
url: "http://jimkeeler.com"

# User settings
username: Jim Keeler
user_description: Principal Product Security Analyst
user_title: Principal Product Security Analyst
title: "Jim Keeler - Principal Product Security Analyst"

# Build settings
markdown: kramdown
permalink: pretty
