# Site settings
description: "Senior Security Engineer"
baseurl: ""
url: "http://jimkeeler.com"

# User settings
username: Jim Keeler
user_description: Senior Security Engineer
user_title: Senior Security Engineer
title: "Jim Keeler - Senior Security Engineer"

# Build settings
markdown: kramdown
permalink: pretty
