# Site settings
title: "Jim Keeler"
email: jim@jimkeeler.com
description: "Jim Keeler's personal tech blog."
baseurl: ""
url: "http://jimkeeler.com"
twitter_username: jimkeeler
github_username:  jimkeeler

# Build settings
markdown: kramdown
permalink: pretty
